pull_request_rules:
  - name: automatic merge for update flake pull requests
    # プルリクエストが特定のルールに一致しているか
    conditions:
      - author~=^turtton$
      - check-success = Checks all workflows passed
    # プルリクエストがルールに一致している場合に実行されるアクション
    actions:
      # ベースのブランチにプルリクエストをマージ
      merge:
        method: merge
