[ghr]
src.github_tag = "siketyan/ghr"
fetch.github = "siketyan/ghr"

# https://github.com/NixOS/nixpkgs/issues/383059
[rustowl]
src.github = "cordx56/rustowl"
fetch.github = "cordx56/rustowl"

[wallpaper-springcity]
src.github = "MrVivekRajan/Hypr-Dots"
fetch.url = "https://raw.githubusercontent.com/MrVivekRajan/Hypr-Dots/refs/heads/Type-2/Spring-City/.config/swww/wall.png"

[jetbrains-dolphin]
src.github = "alex1701c/JetBrainsDolphinPlugin"
fetch.github = "alex1701c/JetBrainsDolphinPlugin"
git.fetchSubmodules = true

[jetbrains-nautilus]
src.git = "https://github.com/encounter/jetbrains-nautilus.git"
fetch.github = "encounter/jetbrains-nautilus"

[hyprpanel-tokyonight]
src.git = "https://github.com/Jas-SinghFSU/HyprPanel.git"
fetch.github = "Jas-SinghFSU/HyprPanel"
extract = ["themes/tokyo_night.json"]
