{ lib, ... }:
{
  options.packs.opencode = {
    omoOverrides = lib.mkOption {
      type = lib.types.attrsOf lib.types.anything;
      default = { };
      description = ''
        Per-host overrides deep-merged into the "[opencode]" harness section of
        ~/.omo/omo.jsonc (generated by home-manager/cli/dev/omo).
        Intended for host-specific model assignments, e.g.:
          packs.opencode.omoOverrides = {
            agents.sisyphus.model = "cli-proxy-api/kimi-k3";
            categories.quick.model = "cli-proxy-api/deepseek-v4-flash";
          };
      '';
    };
  };
}
