# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  beutl = {
    pname = "beutl";
    version = "v1.0.5";
    src = fetchFromGitHub {
      owner = "b-editor";
      repo = "beutl";
      rev = "v1.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-Lv04ep6VcoY19NrgnV/HgcyGrKDFjFczZdurLbZ0X60=";
    };
  };
  ghr = {
    pname = "ghr";
    version = "v0.4.5";
    src = fetchFromGitHub {
      owner = "siketyan";
      repo = "ghr";
      rev = "v0.4.5";
      fetchSubmodules = false;
      sha256 = "sha256-8DnujtAtJiSnrC3k5vGRQuk6RfC5Vn+z4HAVsEnXN7c=";
    };
  };
  jetbrains-dolphin = {
    pname = "jetbrains-dolphin";
    version = "1.4.2";
    src = fetchFromGitHub {
      owner = "alex1701c";
      repo = "JetBrainsDolphinPlugin";
      rev = "1.4.2";
      fetchSubmodules = true;
      sha256 = "sha256-T8ueCqYIKDRo4Ds/o0dCeNjK3dD8fNT9oNEDfzqLg0Y=";
    };
  };
  jetbrains-nautilus = {
    pname = "jetbrains-nautilus";
    version = "c79f6ab6504bd1f1a9d1068f284c24f3227f51c1";
    src = fetchFromGitHub {
      owner = "encounter";
      repo = "jetbrains-nautilus";
      rev = "c79f6ab6504bd1f1a9d1068f284c24f3227f51c1";
      fetchSubmodules = false;
      sha256 = "sha256-f78dMegKVe2fed5I0ogiaG+s9DkSF13s59fhhTr5U5c=";
    };
    date = "2021-05-17";
  };
  rustowl = {
    pname = "rustowl";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "cordx56";
      repo = "rustowl";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-7i/dP+8YuFn7AUXklvMrSefZok1VpnRLmga0XuFudTg=";
    };
  };
  wallpaper-springcity = {
    pname = "wallpaper-springcity";
    version = "Golden-hour-latest";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/MrVivekRajan/Hypr-Dots/refs/heads/Type-2/Spring-City/.config/swww/wall.png";
      sha256 = "sha256-mpsBjyOWLkITiGqHEWHQJacqrNvOaUSm7We5QOiDiww=";
    };
  };
}
