# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ghr = {
    pname = "ghr";
    version = "v0.4.4";
    src = fetchFromGitHub {
      owner = "siketyan";
      repo = "ghr";
      rev = "v0.4.4";
      fetchSubmodules = false;
      sha256 = "sha256-L9+rcdt+MGZSCOJyCE4t/TT6Fjtxvfr9LBJYyRrx208=";
    };
  };
  jetbrains-dolphin = {
    pname = "jetbrains-dolphin";
    version = "1.4.2";
    src = fetchFromGitHub {
      owner = "alex1701c";
      repo = "JetBrainsDolphinPlugin";
      rev = "1.4.2";
      fetchSubmodules = true;
      sha256 = "sha256-T8ueCqYIKDRo4Ds/o0dCeNjK3dD8fNT9oNEDfzqLg0Y=";
    };
  };
  wallpaper-springcity = {
    pname = "wallpaper-springcity";
    version = "Golden-hour-latest";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/MrVivekRajan/Hypr-Dots/refs/heads/Type-2/Spring-City/.config/swww/wall.png";
      sha256 = "sha256-mpsBjyOWLkITiGqHEWHQJacqrNvOaUSm7We5QOiDiww=";
    };
  };
}
