# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  beutl = {
    pname = "beutl";
    version = "v1.0.6";
    src = fetchFromGitHub {
      owner = "b-editor";
      repo = "beutl";
      rev = "v1.0.6";
      fetchSubmodules = false;
      sha256 = "sha256-XuEwq3O0QyqwI6FHw4kcg8FqCjX9AWeHxcrTnVFPpt0=";
    };
  };
  beutl-native-deps = {
    pname = "beutl-native-deps";
    version = "339ad822e77365a652a0d9ac12d235ab2c53b77f";
    src = fetchFromGitHub {
      owner = "b-editor";
      repo = "beutl-native-deps";
      rev = "339ad822e77365a652a0d9ac12d235ab2c53b77f";
      fetchSubmodules = false;
      sha256 = "sha256-kw8LuIu+Ygl795A5ASuStH7EpYcbtjcyhRgYc4R4jVc=";
    };
    date = "2025-03-15";
  };
  jetbrains-dolphin = {
    pname = "jetbrains-dolphin";
    version = "1.4.2";
    src = fetchFromGitHub {
      owner = "alex1701c";
      repo = "JetBrainsDolphinPlugin";
      rev = "1.4.2";
      fetchSubmodules = true;
      sha256 = "sha256-T8ueCqYIKDRo4Ds/o0dCeNjK3dD8fNT9oNEDfzqLg0Y=";
    };
  };
  jetbrains-nautilus = {
    pname = "jetbrains-nautilus";
    version = "c79f6ab6504bd1f1a9d1068f284c24f3227f51c1";
    src = fetchFromGitHub {
      owner = "encounter";
      repo = "jetbrains-nautilus";
      rev = "c79f6ab6504bd1f1a9d1068f284c24f3227f51c1";
      fetchSubmodules = false;
      sha256 = "sha256-f78dMegKVe2fed5I0ogiaG+s9DkSF13s59fhhTr5U5c=";
    };
    date = "2021-05-17";
  };
  wallpaper-springcity = {
    pname = "wallpaper-springcity";
    version = "Golden-hour-latest";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/MrVivekRajan/Hypr-Dots/refs/heads/Type-2/Spring-City/.config/swww/wall.png";
      sha256 = "sha256-mpsBjyOWLkITiGqHEWHQJacqrNvOaUSm7We5QOiDiww=";
    };
  };
}
