set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g status on
set -g status-interval 30
set -g status-position bottom
set -g status-justify left

# Catppuccin Mocha
set -g status-style "bg=#181825,fg=#cdd6f4"

set -g status-left "#[bg=#89b4fa,fg=#11111b,bold]  #S #[bg=#181825,fg=#89b4fa]"
set -g status-left-length 30

set -g status-right "#[fg=#585b70]#[bg=#585b70,fg=#cdd6f4]  󰙜 #(cat __PORT_FILE__) │  #(cat __QUOTA_FILE__) #[fg=#89b4fa]#[bg=#89b4fa,fg=#11111b,bold]  %H:%M "
set -g status-right-length 100

set -g window-status-format "#[fg=#585b70,bg=#181825] #I #W "
set -g window-status-current-format "#[bg=#313244,fg=#b4befe,bold] #I #W "
set -g window-status-separator ""

set -g pane-border-style "fg=#45475a"
set -g pane-active-border-style "fg=#89b4fa"

set -g message-style "bg=#313244,fg=#cdd6f4"
set -g message-command-style "bg=#313244,fg=#cdd6f4"

set -g mode-style "bg=#585b70,fg=#cdd6f4"

set -g clock-mode-colour "#89b4fa"
